spring.application.name=car-service
server.port=8081

phone.service.url=http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,metrics" 
  endpoint:
    loggers:
      enabled: true

springdoc:
  show-actuator: true 
  swagger-ui:
    path: /swagger-ui.html